apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxv2
  namespace: trivago-app
spec:
  selector:
    matchLabels:
      app: nginxv2
  replicas: 2
  template:
    metadata:
      labels:
        app: nginxv2
    spec:
      containers:
      - name: nginxv2
        image: manouchehrsolamani/trivago:v2
        ports:
        - name: web
          containerPort: 80
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 3
          timeoutSeconds: 1
          failureThreshold: 1
          successThreshold: 1
          httpGet:
            port: 80
            path: /
        livenessProbe:
          initialDelaySeconds: 1
          periodSeconds: 3
          timeoutSeconds: 1
          failureThreshold: 1
          successThreshold: 1
          httpGet:
            port: 80
            path: /
