apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress2
  namespace: trivago-app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: trivago.de
    http:
      paths:
        - backend:
            service:
              name: nginxv2-svc
              port:
                number: 80
          path: /
          pathType: Exact
     