apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxv1
  namespace: trivago-app
spec:
  selector:
    matchLabels:
      app: nginxv1
  replicas: 2
  template:
    metadata:
      labels:
        app: nginxv1
    spec:
      containers:
      - name: nginxv1
        image: manouchehrsolamani/trivago:v10
        ports:
        - name: web
          containerPort: 80
        readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 3
          timeoutSeconds: 1
          failureThreshold: 1
          successThreshold: 1
          httpGet:
            port: 80
            path: /
        livenessProbe:
          initialDelaySeconds: 1
          periodSeconds: 3
          timeoutSeconds: 1
          failureThreshold: 1
          successThreshold: 1
          httpGet:
            port: 80
            path: /