apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-ingress1
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "50"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: trivago.de
    http:
      paths:
        - backend:
            service:
              name: nginxv1-svc
              port:
                number: 80
          path: /
          pathType: Exact
        # - backend:
            # service:
              # name: web2
              # port:
                # number: 8080