apiVersion: v1
kind: Secret
metadata:
  name: trivago-tls-secret
type: kubernetes.io/tls

data:
  tls.crt: |
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCfFzqXnLUoJXgg
    FGHxuzTS6IdHyWx+G+u90btcADaP7wOVFuPPqdQwSPwTuVczZelyNDg0sPh/TtFW
    sWRHKrVQibl48s7FEx8hW/rDm1um9dvnWwZJhHyGh07Ce7d0hKfOkd1QVS/LcjxH
    cpE7LG/eaYudLqmTLdVdqkrjibeztyAoj6NVBcq6VhD3V4MjpM2GOdoGWWhDfGuy
    eq0q5s6+KSIMw3tmAPV7TkIwLDGTmIJpVRLSJfk1MZaveGlWYBS1qHMnv0w28EK0
    j5QS4gZs2S3fYEjAl14uSujgTAQUXp6ajzJqgCmE2j/AknrdsKzZTh8IeD/rOLhD
    mLmtsNz3AgMBAAECggEAAIcho0ZylnGKxkpx+prUHtooZjM+dOku+rXKoHvs6hKP
    2OMF3EeTGvrHMDVkPID8q4H1mhKEXVAevLWCbuoEQuR/E+L2Lt+1BTpjRvY8XQGD
    P/FS/2+9GVbLVPmEOkEfASBIzURrUrqWelpiYcnLNBHGKWU0rM3ZBqJNb0eqKaYx
    xp/7IGVsMXOr22++Xo7sd++FNTUY4XPKt7cMjRoYZQQDK9mQtV2Xdi4ULbRXOz5i
    ISewVdbYqXWUd5wVJ7OhM8BZ1Eq6bCQ5eMFQl1GARGH/oyLhMiEk09OkL05glowd
    gDkq5GYmUzH5Bm7C2Qw1ru0x0l/MXjpQMyiPmVdEAQKBgQDVT8Z9fK5Vvm/SvSKk
    RhdishuwfLjNvHg/hf388CgRFAYeo21/dmQPjvlnJe9ussG3W9+FMAGTm3m55q9I
    hnY+LlTwbnR0EuD99J3nTAEtiWgQ8jRP7YfLqJhX81ZLmvGDOZbh9dFsKL4GSodD
    gmvEptvUX/pQmZS4AcaLO7s8gQKBgQC+7aYfMMJkFjK1wc73HRIlZddoSdTP96dK
    griAe4liGRt9mhXbEgg8DG/4x0na6coeynuCweK7XsYcSb39k659X8GlQGHbLYBM
    veRZ7bSh6h/fqxQr+6TmR9vGTnk5McGcLLCI09KjndMB6EU4rG8lNFA97PLkVZTt
    MHo9Ib09dwKBgQDVIEfpyVFGSmff3ylliMKE0f/objUXGl/q2C3VMv5VUfRrWE5n
    NBr1kJyP+s8ng2MZmKnToQtyN71/iIVJqU8rAY/MShAAiXxTQL0kBESJAuj/RYAO
    +/zZ9zF/bpmiIMV9n2Spj7oWnv59uqk7Qmv6p9ysbNjk/w4ga2W8Z4nEAQKBgHyU
    ABLV8+DugwQJg4vGEjMIsna/xfY0t5lslgpvkQLLMx7PTXd12p2j1+PR1STb6yAQ
    Kmr1K4XqnwWSMD+m/vGba3Tx/2fN1qs8NCVhbr0/ULDWpgDU35HKTWKljX9+McA/
    gKim3ggYULgr4A7MpHD4I2tkkk/eb6AcQ4Zj32CdAoGBAIKrlKePV5/TiXZ9aOq8
    myXKuWvSJlzKWafTVaeif1AQwa9bPmvTaU22cFtYjBsQCxvh0y0xEexaKB4zRLCb
    CX3ZSyxZJYemd/xZIngT2Ov3zGaHIKCfK5LEqXDmte+ev3BXxgK1KKVrtbRl+P8f
    1YFEtiKQpze6AYw6JtydHh4/
  tls.key: |
    MIIDNTCCAh2gAwIBAgIUZCWabLLUvXkrWZTgGggYRCJTrY0wDQYJKoZIhvcNAQEL
    BQAwKjETMBEGA1UEAwwKdHJpdmFnby5kZTETMBEGA1UECgwKdHJpdmFnby5kZTAe
    Fw0yMzA2MTQyMjQzMTFaFw0yNDA2MTMyMjQzMTFaMCoxEzARBgNVBAMMCnRyaXZh
    Z28uZGUxEzARBgNVBAoMCnRyaXZhZ28uZGUwggEiMA0GCSqGSIb3DQEBAQUAA4IB
    DwAwggEKAoIBAQCfFzqXnLUoJXggFGHxuzTS6IdHyWx+G+u90btcADaP7wOVFuPP
    qdQwSPwTuVczZelyNDg0sPh/TtFWsWRHKrVQibl48s7FEx8hW/rDm1um9dvnWwZJ
    hHyGh07Ce7d0hKfOkd1QVS/LcjxHcpE7LG/eaYudLqmTLdVdqkrjibeztyAoj6NV
    Bcq6VhD3V4MjpM2GOdoGWWhDfGuyeq0q5s6+KSIMw3tmAPV7TkIwLDGTmIJpVRLS
    Jfk1MZaveGlWYBS1qHMnv0w28EK0j5QS4gZs2S3fYEjAl14uSujgTAQUXp6ajzJq
    gCmE2j/AknrdsKzZTh8IeD/rOLhDmLmtsNz3AgMBAAGjUzBRMB0GA1UdDgQWBBQE
    eRc7hpcqTR54c2rzvsUqoDcl5TAfBgNVHSMEGDAWgBQEeRc7hpcqTR54c2rzvsUq
    oDcl5TAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAMjW+VW5aw
    +W2FNV95JQRU2SgewnzyiXs3OH2mDJ+saUotyxpULdQRv+oHEBLoGauwXlbPwsXs
    pApkTM8TqblRKQ+amYOfYLOwU0gpDMqkVYybkzLQr39Zb4j+nRbjZk6weE2z7nv6
    X+K+TfyJD2i/QbGwZRP/4dSuByUERjajquYtxAINyBiJ+CVkdk4A6JQMuVhpj8hs
    BLSeGcq3IZf80ZVGX3X3mEuoWigxyNm8hl1bDzLJuNkLfCRb4g6xYzHxvaZ9coWp
    RS13NYUbnkFuk4NFWtUTqYMqhNLcSRV3czE38j+qYcVDJG5m40ufxRnfTAeEUnur
    uraRgo0rl7WF