apiVersion: v1
kind: Service
metadata:
  name: nginxv1-svc
  namespace: trivago-app
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginxv1